#!/bin/bash -e
#
# zLog - lt (log time):
# log time create .md file with current Ymd and appends a message to it
#
# Copyright (c) 2019 - Panajotis Zamos <panos@holisticagency.com>
#
# Built with shell-script-skeleton v0.0.3 <http://github.com/z017/shell-script-skeleton>
#
# TODO:
# - [ ] check default folder if exists
# - [ ] add -t NN to offset NN minutes
# - [x] add -e for edit mode --DONE
# - [ ] add option to less some of the previous days
# - [ ] handle special characters in arguments `tb cashier upgrade 7 -> 9 and dinner` will echo to file `9`

readonly SCRIPT_NAME=${0##*/}

TILE_N=15
#RED='\033[0;31m'
#YELLOW='\033[0;33m'
#NC='\033[0m' # No Color

folder="$HOME/Dropbox/logtime/"
date_name=$(date '+%Y-%m-%d')
time_name=$(date '+%T')

ext=".md"

fullname="$folder$date_name$ext"

#######################################
# help command
#######################################
function help_command() {
  cat <<END;
USAGE:
  $SCRIPT_NAME [options] <command>
OPTIONS:
  -e                      Edit
  -l                      List last 100 logtimes
  -?                      Alias help command
  --version, -v           Alias version command
  --force                 Don't ask for confirmation
  --                      Denotes the end of the options.  Arguments after this
                          will be handled as parameters even if they start with
                          a '-'.
COMMANDS:
  help                    Display detailed help
  version                 Print version information.
END
  exit 1
}


if [ $1 ] ;then
    if [ "$1" == -? ];then
        help_command
    elif [ "$1" == -e ];then
        editor $fullname
    elif [ "$1" == -l ];then
        tail -n 100 "$fullname"
    else
        echo $time_name $@ >> $fullname
        tail -n "$TILE_N" "$fullname"
    fi
else
    #read -p 'log: ' log
    #echo "$time_name $log" >> $fullname

    while IFS= read -p 'log: ' -r log && [ -n "$log" ]; do
        echo "$time_name $log" >> $fullname
    done

    echo "============ $fullname ============"
    tail -n "$TILE_N" "$fullname"
fi

